# output_dir: /work/microbiome/msingle/mess/116_smafa_naive_metapackage/20221209/output_dir_real
output_dir: /work/microbiome/msingle/mess/116_smafa_naive_metapackage/20221209/output_dir
metapackage: /home/woodcrob/git/singlem/db/S3.0.5.metapackage20220806.smpkg.zb/payload_directory
new_metapackage: S3.1.0.metapackage_20221209.smpkg
# untarred ~/m/db/gtdb/gtdb_release207/genomic_files_reps/gtdb_proteins_aa_reps_r207.tar.gz
# gtdb_protein_faa_reps: /work/microbiome/db/gtdb/gtdb_release207/genomic_files_reps/protein_faa_reps
gtdb_protein_faa_reps: /home/woodcrob/git/singlem/extras/update_metapackage/test_protein_faa_reps2
gtdb_bac_tax: /work/microbiome/db/gtdb/gtdb_release207/bac120_taxonomy_r207.tsv
gtdb_arc_tax: /work/microbiome/db/gtdb/gtdb_release207/ar53_taxonomy_r207.tsv
pfams: /work/microbiome/msingle/sam/HMMs/Pfam
tigrfams: /work/microbiome/msingle/sam/HMMs/TIGRfams.HMM
uniprot_seq: /work/microbiome/abisko/aroneys/uniprot/uniref100_20210616/uniprot_sprot.fa
uniprot_tax: /work/microbiome/abisko/aroneys/uniprot/uniref100_20210616/uniprot_sprot_taxonomy.tsv
sra_seqs_1:
  DRR083195: /work/microbiome/msingle/sam/SRA/DRR083195_1.fastq
  SRR1926147: /work/microbiome/msingle/sam/SRA/SRR1926147_1.fastq
  SRR9224014: /work/microbiome/msingle/sam/SRA/SRR9224014_1.fastq
sra_seqs_2:
  DRR083195: /work/microbiome/msingle/sam/SRA/DRR083195_2.fastq
  SRR1926147: /work/microbiome/msingle/sam/SRA/SRR1926147_2.fastq
  SRR9224014: /work/microbiome/msingle/sam/SRA/SRR9224014_2.fastq
gtdb_sp_clusters: /work/microbiome/db/gtdb/gtdb_release207/auxillary_files/sp_clusters_r207.tsv
gtdb_bac_metadata: /work/microbiome/db/gtdb/gtdb_release207/bac120_metadata_r207.tsv
gtdb_arc_metadata: /work/microbiome/db/gtdb/gtdb_release207/ar53_metadata_r207.tsv
gtdb_protein_fna_reps: /work/microbiome/db/gtdb/gtdb_release207/genomic_files_reps/protein_fna_reps/
gtdb_protein_fna_reps: /home/woodcrob/git/singlem/extras/update_metapackage/test_protein_fna_reps2
